{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"metadata":{"role":"collection","externalID":"KeystoneCrypto","modules":[{"name":"KeystoneCrypto"}],"title":"KeystoneCrypto","symbolKind":"module","roleHeading":"Framework"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/KeystoneCrypto","doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/LocalKey","doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/OneTimeKey","doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/Pinblock"]},{"identifiers":["doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/KeystoneExceptions"],"title":"Enumerations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keystonecrypto"]},{"paths":["\/documentation\/keystonecrypto"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.KeystoneCrypto/documentation/KeystoneCrypto/KeystoneCryptoVersionNumber":{"title":"KeystoneCryptoVersionNumber","fragments":[{"kind":"identifier","text":"KeystoneCryptoVersionNumber"}],"identifier":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/KeystoneCryptoVersionNumber","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/keystonecrypto\/keystonecryptoversionnumber","abstract":[]},"doc://org.cocoapods.KeystoneCrypto/documentation/KeystoneCrypto/Pinblock":{"navigatorTitle":[{"text":"Pinblock","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/keystonecrypto\/pinblock","kind":"symbol","identifier":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/Pinblock","title":"Pinblock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pinblock","kind":"identifier"}]},"doc://org.cocoapods.KeystoneCrypto/documentation/KeystoneCrypto/KeystoneCryptoVersionString":{"type":"topic","identifier":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/KeystoneCryptoVersionString","fragments":[{"text":"KeystoneCryptoVersionString","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/keystonecrypto\/keystonecryptoversionstring","role":"symbol","title":"KeystoneCryptoVersionString"},"doc://org.cocoapods.KeystoneCrypto/documentation/KeystoneCrypto":{"type":"topic","title":"KeystoneCrypto","kind":"symbol","url":"\/documentation\/keystonecrypto","role":"collection","abstract":[],"identifier":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto"},"doc://org.cocoapods.KeystoneCrypto/documentation/KeystoneCrypto/LocalKey":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocalKey","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/LocalKey","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocalKey"}],"url":"\/documentation\/keystonecrypto\/localkey","abstract":[],"title":"LocalKey","type":"topic"},"doc://org.cocoapods.KeystoneCrypto/documentation/KeystoneCrypto/KeystoneExceptions":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeystoneExceptions"}],"navigatorTitle":[{"text":"KeystoneExceptions","kind":"identifier"}],"url":"\/documentation\/keystonecrypto\/keystoneexceptions","identifier":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/KeystoneExceptions","abstract":[],"kind":"symbol","title":"KeystoneExceptions","role":"symbol"},"doc://org.cocoapods.KeystoneCrypto/documentation/KeystoneCrypto/KeystoneCrypto":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeystoneCrypto"}],"navigatorTitle":[{"kind":"identifier","text":"KeystoneCrypto"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/KeystoneCrypto","role":"symbol","type":"topic","kind":"symbol","title":"KeystoneCrypto","url":"\/documentation\/keystonecrypto\/keystonecrypto"},"doc://org.cocoapods.KeystoneCrypto/documentation/KeystoneCrypto/OneTimeKey":{"identifier":"doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/OneTimeKey","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OneTimeKey"}],"url":"\/documentation\/keystonecrypto\/onetimekey","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OneTimeKey"}],"abstract":[],"title":"OneTimeKey","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/KeystoneCryptoVersionNumber","doc:\/\/org.cocoapods.KeystoneCrypto\/documentation\/KeystoneCrypto\/KeystoneCryptoVersionString"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"}]}]}